
import { Doctor } from './types/doctors';
import { Lab } from './types/labs';
import { MedicalStore } from './types/medical-stores';
import { YogaCenter } from './types/yoga';


export const seedDoctors: Doctor[] = [
  {
    id: "doc1",
    name: "Dr. Alok Gupta",
    clinicName: "Gupta Health Clinic",
    qualification: "MBBS, MD (Cardiology)",
    specialization: "Cardiologist",
    experience: 15,
    consultationFee: 800,
    contact: "9876543210",
    location: "Sigra, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Renowned cardiologist with 15 years of experience in treating heart conditions.",
    userId: "seed_doc1",
    updatedAt: new Date(),
  },
  {
    id: "doc2",
    name: "Dr. Priya Singh",
    clinicName: "Skin & Care Clinic",
    qualification: "MBBS, DDVL",
    specialization: "Dermatologist",
    experience: 8,
    consultationFee: 600,
    contact: "9876543211",
    location: "Lanka, Varanasi",
     availableTimeSlots: {
      weekdays: { morning: "11:00 AM - 2:00 PM", evening: "6:00 PM - 9:00 PM" },
      weekends: { morning: "10:00 AM - 1:00 PM", evening: "Closed" },
    },
    bio: "Specializes in all types of skin and hair treatments.",
    userId: "seed_doc2",
    updatedAt: new Date(),
  },
  {
    id: "doc3",
    name: "Dr. Rajesh Kumar",
    clinicName: "Child Care Center",
    qualification: "MBBS, DCH",
    specialization: "Pediatrician",
    experience: 12,
    consultationFee: 500,
    contact: "9876543212",
    location: "Mahmoorganj, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9:00 AM - 12:00 PM", evening: "4:00 PM - 7:00 PM" },
      weekends: { morning: "9:00 AM - 1:00 PM", evening: "Closed" },
    },
    bio: "Dedicated pediatrician focused on child wellness and development.",
    userId: "seed_doc3",
    updatedAt: new Date(),
  },
   {
    id: "doc4",
    name: "Dr. Anita Verma",
    clinicName: "Verma Dental Care",
    qualification: "BDS, MDS",
    specialization: "Dentist",
    experience: 10,
    consultationFee: 400,
    contact: "9876543213",
    location: "Pandeypur, Varanasi",
     availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "10:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Expert in dental procedures including root canals, implants, and cosmetic dentistry.",
    userId: "seed_doc4",
    updatedAt: new Date(),
  },
  // --- New Doctors from Apex Super Speciality Hospital ---
  {
    id: "doc5",
    name: "Dr. Santosh Kumar Singh",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 20,
    consultationFee: 1000,
    contact: "9123456780",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 12 PM", evening: "4 PM - 6 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Chairman at Apex. Specializes in Joint Replacement, Spine, and Arthroscopy.",
    userId: "seed_doc5",
    updatedAt: new Date(),
  },
  {
    id: "doc6",
    name: "Dr. Swaroop Patel",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 18,
    consultationFee: 950,
    contact: "9123456781",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 7 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Director at Apex. Focus on Joint Replacement, Spine, and Arthroscopy.",
    userId: "seed_doc6",
    updatedAt: new Date(),
  },
  {
    id: "doc7",
    name: "Dr. Amit Kr. Jha",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 15,
    consultationFee: 900,
    contact: "9123456782",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "4 PM - 8 PM" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Expert in Joint Replacement, Spine, and Arthroscopy at Apex Hospital.",
    userId: "seed_doc7",
    updatedAt: new Date(),
  },
  {
    id: "doc8",
    name: "Dr. Ankita Patel",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MD (Radiation Oncology)",
    specialization: "Radiation Oncology",
    experience: 16,
    consultationFee: 900,
    contact: "9123456783",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 4 PM", evening: "" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Director of Radiation Oncology at Apex Hospital.",
    userId: "seed_doc8",
    updatedAt: new Date(),
  },
  {
    id: "doc9",
    name: "Dr. Satish Kumar",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "DM (Neurology)",
    specialization: "Neurology",
    experience: 14,
    consultationFee: 850,
    contact: "9123456784",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "11 AM - 2 PM", evening: "6 PM - 8 PM" },
      weekends: { morning: "11 AM - 1 PM", evening: "Closed" },
    },
    bio: "Consultant Neurologist at Apex Super Speciality Hospital.",
    userId: "seed_doc9",
    updatedAt: new Date(),
  },
  {
    id: "doc10",
    name: "Dr. Anand Kumar",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (General Surgery)",
    specialization: "General Surgery",
    experience: 13,
    consultationFee: 700,
    contact: "9123456785",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "5 PM - 8 PM" },
      weekends: { morning: "10 AM - 12 PM", evening: "Closed" },
    },
    bio: "General and Laparoscopic Surgeon at Apex Hospital.",
    userId: "seed_doc10",
    updatedAt: new Date(),
  },
  {
    id: "doc11",
    name: "Dr. Amit Srivastava",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MCh (CTVS)",
    specialization: "Cardiothoracic & Vascular Surgery",
    experience: 17,
    consultationFee: 1200,
    contact: "9123456786",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 2 PM", evening: "By Appointment" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Head of Cardiothoracic and Vascular Surgery at Apex Hospital.",
    userId: "seed_doc11",
    updatedAt: new Date(),
  },
  {
    id: "doc12",
    name: "Dr. P. K. Keshari",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MCh (Urology)",
    specialization: "Urology",
    experience: 19,
    consultationFee: 950,
    contact: "9123456787",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 7 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Senior Urologist at Apex Hospital.",
    userId: "seed_doc12",
    updatedAt: new Date(),
  },
  // --- New Doctors from Popular Hospital ---
  {
    id: "doc13",
    name: "Dr. Urmila",
    clinicName: "Popular Hospital Varanasi",
    qualification: "MD (Obstetrics & Gynecology)",
    specialization: "Gynecology",
    experience: 25,
    consultationFee: 750,
    contact: "9234567890",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "11 AM - 3 PM", evening: "Closed" },
      weekends: { morning: "11 AM - 1 PM", evening: "Closed" },
    },
    bio: "Senior Gynecologist at Popular Hospital with over 30 years of service.",
    userId: "seed_doc13",
    updatedAt: new Date(),
  },
  // --- New Doctors from Peace Point Hospitals ---
  {
    id: "doc14",
    name: "Peace Point Pediatrics",
    clinicName: "Peace Point Hospitals Pvt. Ltd.",
    qualification: "MD (Pediatrics)",
    specialization: "Pediatrics",
    experience: 15,
    consultationFee: 650,
    contact: "9345678901",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 5 PM", evening: "" },
      weekends: { morning: "10 AM - 2 PM", evening: "" },
    },
    bio: "Specialized care for children at Peace Point Hospitals.",
    userId: "seed_doc14",
    updatedAt: new Date(),
  },
  // --- New Doctors from Private Clinics ---
  {
    id: "doc15",
    name: "Dr. S. S. Behera",
    clinicName: "Dr. S. S. Behera Clinic",
    qualification: "DM (Gastroenterology), DM (Nephrology)",
    specialization: "Gastroenterologist & Nephrologist",
    experience: 22,
    consultationFee: 1100,
    contact: "9456789012",
    location: "Indira Nagar Colony, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "Closed", evening: "5 PM - 9 PM" },
      weekends: { morning: "10 AM - 2 PM", evening: "Closed" },
    },
    bio: "A top gastroenterologist and nephrologist with a private clinic.",
    userId: "seed_doc15",
    updatedAt: new Date(),
  },
  {
    id: "doc16",
    name: "Dr. Kumar Ashish",
    clinicName: "Neuro Speciality Clinic",
    qualification: "MCh (Neuro-surgery)",
    specialization: "Neurosurgeon",
    experience: 18,
    consultationFee: 1200,
    contact: "9567890123",
    location: "Shivdaspur, Manduwadih, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 8 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Consultant neurosurgeon with a specialty clinic in Shivdaspur.",
    userId: "seed_doc16",
    updatedAt: new Date(),
  },
  {
    id: "doc17",
    name: "Dr. Ravi Ranjan Sharma",
    clinicName: "Mahamana Clinic",
    qualification: "MD (Internal Medicine)",
    specialization: "General Physician",
    experience: 10,
    consultationFee: 550,
    contact: "9678901234",
    location: "Lanka, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "6 PM - 9 PM" },
      weekends: { morning: "9 AM - 1 PM", evening: "Closed" },
    },
    bio: "MD specializing in fever, diabetes, hypertension, and rheumatic diseases.",
    userId: "seed_doc17",
    updatedAt: new Date(),
  },
];


export const seedLabs: Lab[] = [
    {
        id: "lab1",
        labName: "Modern Pathology Lab",
        technicianName: "Mr. Rakesh Singh",
        address: "Bhelupur, Varanasi",
        registrationID: "LABVNS001",
        services: "Blood Test, Urine Test, Sugar Test, Thyroid Profile",
        charges: "Varies per test. Basic blood test starts at ₹150.",
        homeCollection: true,
        userId: "seed_lab1",
        updatedAt: new Date(),
    },
     {
        id: "lab2",
        labName: "Accurate Diagnostics",
        technicianName: "Ms. Sunita Patel",
        address: "Lanka, Varanasi",
        registrationID: "LABVNS002",
        services: "X-Ray, Ultrasound, CT Scan, MRI",
        charges: "X-Ray starts at ₹300. Advanced imaging as per rate card.",
        homeCollection: false,
        userId: "seed_lab2",
        updatedAt: new Date(),
    },
     {
        id: "lab3",
        labName: "Varanasi Health Scans",
        technicianName: "Mr. Anand Kumar",
        address: "Mahmoorganj, Varanasi",
        registrationID: "LABVNS003",
        services: "Full Body Checkup, Cardiac Markers, Cancer Markers",
        charges: "Health packages start from ₹999.",
        homeCollection: true,
        userId: "seed_lab3",
        updatedAt: new Date(),
    }
];

export const seedMedicalStores: MedicalStore[] = [
    {
        id: "ms1",
        storeName: "Apollo Pharmacy",
        ownerName: "Mr. Suresh Gupta",
        address: "Sigra, Varanasi",
        licenseNo: "UPVNS12345",
        contact: "8876543210",
        offers: "15% off on all medicines",
        userId: "seed_ms1",
        updatedAt: new Date(),
    },
    {
        id: "ms2",
        storeName: "Jeevan Medicals",
        ownerName: "Mr. Dinesh Sharma",
        address: "Lanka, Varanasi",
        licenseNo: "UPVNS67890",
        contact: "8876543211",
        offers: "24/7 Service Available",
        userId: "seed_ms2",
        updatedAt: new Date(),
    },
    {
        id: "ms3",
        storeName: "Kashi Medicos",
        ownerName: "Mr. Rajan Mishra",
        address: "Chowk, Varanasi",
        licenseNo: "UPVNS11223",
        contact: "8876543212",
        offers: "Free home delivery within 5km",
        userId: "seed_ms3",
        updatedAt: new Date(),
    }
];

export const seedYogaCenters: YogaCenter[] = [
    {
        id: "yoga1",
        centerName: "Kashi Yoga Shala",
        instructorName: "Yogi Adityanath",
        address: "Assi Ghat, Varanasi",
        classTypes: "Hatha, Ashtanga, Meditation",
        schedule: "Mon-Sat: 6-8 AM & 5-7 PM",
        fee: "₹2500/month",
        onlineClasses: true,
        bio: "Traditional yoga taught on the serene banks of the Ganges.",
        userId: "seed_yoga1",
        updatedAt: new Date(),
    },
    {
        id: "yoga2",
        centerName: "Varanasi Wellness Center",
        instructorName: "Priya Sharma",
        address: "Nadesar, Varanasi",
        classTypes: "Vinyasa, Power Yoga, Prenatal Yoga",
        schedule: "Mon-Fri: 7-8 AM, 6-7 PM",
        fee: "₹3000/month, ₹400/class",
        onlineClasses: true,
        bio: "A modern studio focusing on fitness and wellness through dynamic yoga flows.",
        userId: "seed_yoga2",
        updatedAt: new Date(),
    }
];
