
import { Ambulance } from './types/ambulance';
import { Doctor } from './types/doctors';
import { Lab } from './types/labs';
import { MedicalStore } from './types/medical-stores';
import { YogaCenter } from './types/yoga';


export const seedDoctors: Doctor[] = [
  {
    id: "doc1",
    name: "Dr. Alok Gupta",
    clinicName: "Gupta Health Clinic",
    qualification: "MBBS, MD (Cardiology)",
    specialization: "Cardiologist",
    experience: 15,
    consultationFee: 800,
    contact: "9876543210",
    location: "Sigra, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Renowned cardiologist with 15 years of experience in treating heart conditions.",
    userId: "seed_doc1",
    updatedAt: new Date(),
  },
  {
    id: "doc2",
    name: "Dr. Priya Singh",
    clinicName: "Skin & Care Clinic",
    qualification: "MBBS, DDVL",
    specialization: "Dermatologist",
    experience: 8,
    consultationFee: 600,
    contact: "9876543211",
    location: "Lanka, Varanasi",
     availableTimeSlots: {
      weekdays: { morning: "11:00 AM - 2:00 PM", evening: "6:00 PM - 9:00 PM" },
      weekends: { morning: "10:00 AM - 1:00 PM", evening: "Closed" },
    },
    bio: "Specializes in all types of skin and hair treatments.",
    userId: "seed_doc2",
    updatedAt: new Date(),
  },
  {
    id: "doc3",
    name: "Dr. Rajesh Kumar",
    clinicName: "Child Care Center",
    qualification: "MBBS, DCH",
    specialization: "Pediatrician",
    experience: 12,
    consultationFee: 500,
    contact: "9876543212",
    location: "Mahmoorganj, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9:00 AM - 12:00 PM", evening: "4:00 PM - 7:00 PM" },
      weekends: { morning: "9:00 AM - 1:00 PM", evening: "Closed" },
    },
    bio: "Dedicated pediatrician focused on child wellness and development.",
    userId: "seed_doc3",
    updatedAt: new Date(),
  },
   {
    id: "doc4",
    name: "Dr. Anita Verma",
    clinicName: "Verma Dental Care",
    qualification: "BDS, MDS",
    specialization: "Dentist",
    experience: 10,
    consultationFee: 400,
    contact: "9876543213",
    location: "Pandeypur, Varanasi",
     availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "10:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Expert in dental procedures including root canals, implants, and cosmetic dentistry.",
    userId: "seed_doc4",
    updatedAt: new Date(),
  },
  // --- New Doctors from Apex Super Speciality Hospital ---
  {
    id: "doc5",
    name: "Dr. Santosh Kumar Singh",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 20,
    consultationFee: 1000,
    contact: "9123456780",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 12 PM", evening: "4 PM - 6 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Chairman at Apex. Specializes in Joint Replacement, Spine, and Arthroscopy.",
    userId: "seed_doc5",
    updatedAt: new Date(),
  },
  {
    id: "doc6",
    name: "Dr. Swaroop Patel",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 18,
    consultationFee: 950,
    contact: "9123456781",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 7 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Director at Apex. Focus on Joint Replacement, Spine, and Arthroscopy.",
    userId: "seed_doc6",
    updatedAt: new Date(),
  },
  {
    id: "doc7",
    name: "Dr. Amit Kr. Jha",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (Orthopedics)",
    specialization: "Orthopedics",
    experience: 15,
    consultationFee: 900,
    contact: "9123456782",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "4 PM - 8 PM" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Expert in Joint Replacement, Spine, and Arthroscopy at Apex Hospital.",
    userId: "seed_doc7",
    updatedAt: new Date(),
  },
  {
    id: "doc8",
    name: "Dr. Ankita Patel",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MD (Radiation Oncology)",
    specialization: "Radiation Oncology",
    experience: 16,
    consultationFee: 900,
    contact: "9123456783",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 4 PM", evening: "" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Director of Radiation Oncology at Apex Hospital.",
    userId: "seed_doc8",
    updatedAt: new Date(),
  },
  {
    id: "doc9",
    name: "Dr. Satish Kumar",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "DM (Neurology)",
    specialization: "Neurology",
    experience: 14,
    consultationFee: 850,
    contact: "9123456784",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "11 AM - 2 PM", evening: "6 PM - 8 PM" },
      weekends: { morning: "11 AM - 1 PM", evening: "Closed" },
    },
    bio: "Consultant Neurologist at Apex Super Speciality Hospital.",
    userId: "seed_doc9",
    updatedAt: new Date(),
  },
  {
    id: "doc10",
    name: "Dr. Anand Kumar",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MS (General Surgery)",
    specialization: "General Surgery",
    experience: 13,
    consultationFee: 700,
    contact: "9123456785",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "5 PM - 8 PM" },
      weekends: { morning: "10 AM - 12 PM", evening: "Closed" },
    },
    bio: "General and Laparoscopic Surgeon at Apex Hospital.",
    userId: "seed_doc10",
    updatedAt: new Date(),
  },
  {
    id: "doc11",
    name: "Dr. Amit Srivastava",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MCh (CTVS)",
    specialization: "Cardiothoracic & Vascular Surgery",
    experience: 17,
    consultationFee: 1200,
    contact: "9123456786",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 2 PM", evening: "By Appointment" },
      weekends: { morning: "Closed", evening: "Closed" },
    },
    bio: "Head of Cardiothoracic and Vascular Surgery at Apex Hospital.",
    userId: "seed_doc11",
    updatedAt: new Date(),
  },
  {
    id: "doc12",
    name: "Dr. P. K. Keshari",
    clinicName: "Apex Super Speciality Hospital",
    qualification: "MCh (Urology)",
    specialization: "Urology",
    experience: 19,
    consultationFee: 950,
    contact: "9123456787",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 7 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Senior Urologist at Apex Hospital.",
    userId: "seed_doc12",
    updatedAt: new Date(),
  },
  // --- New Doctors from Popular Hospital ---
  {
    id: "doc13",
    name: "Dr. Urmila",
    clinicName: "Popular Hospital Varanasi",
    qualification: "MD (Obstetrics & Gynecology)",
    specialization: "Gynecology",
    experience: 25,
    consultationFee: 750,
    contact: "9234567890",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "11 AM - 3 PM", evening: "Closed" },
      weekends: { morning: "11 AM - 1 PM", evening: "Closed" },
    },
    bio: "Senior Gynecologist at Popular Hospital with over 30 years of service.",
    userId: "seed_doc13",
    updatedAt: new Date(),
  },
  // --- New Doctors from Peace Point Hospitals ---
  {
    id: "doc14",
    name: "Peace Point Pediatrics",
    clinicName: "Peace Point Hospitals Pvt. Ltd.",
    qualification: "MD (Pediatrics)",
    specialization: "Pediatrics",
    experience: 15,
    consultationFee: 650,
    contact: "9345678901",
    location: "Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 5 PM", evening: "" },
      weekends: { morning: "10 AM - 2 PM", evening: "" },
    },
    bio: "Specialized care for children at Peace Point Hospitals.",
    userId: "seed_doc14",
    updatedAt: new Date(),
  },
  // --- New Doctors from Private Clinics ---
  {
    id: "doc15",
    name: "Dr. S. S. Behera",
    clinicName: "Dr. S. S. Behera Clinic",
    qualification: "DM (Gastroenterology), DM (Nephrology)",
    specialization: "Gastroenterologist & Nephrologist",
    experience: 22,
    consultationFee: 1100,
    contact: "9456789012",
    location: "Indira Nagar Colony, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "Closed", evening: "5 PM - 9 PM" },
      weekends: { morning: "10 AM - 2 PM", evening: "Closed" },
    },
    bio: "A top gastroenterologist and nephrologist with a private clinic.",
    userId: "seed_doc15",
    updatedAt: new Date(),
  },
  {
    id: "doc16",
    name: "Dr. Kumar Ashish",
    clinicName: "Neuro Speciality Clinic",
    qualification: "MCh (Neuro-surgery)",
    specialization: "Neurosurgeon",
    experience: 18,
    consultationFee: 1200,
    contact: "9567890123",
    location: "Shivdaspur, Manduwadih, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "10 AM - 1 PM", evening: "5 PM - 8 PM" },
      weekends: { morning: "10 AM - 1 PM", evening: "Closed" },
    },
    bio: "Consultant neurosurgeon with a specialty clinic in Shivdaspur.",
    userId: "seed_doc16",
    updatedAt: new Date(),
  },
  {
    id: "doc17",
    name: "Dr. Ravi Ranjan Sharma",
    clinicName: "Mahamana Clinic",
    qualification: "MD (Internal Medicine)",
    specialization: "General Physician",
    experience: 10,
    consultationFee: 550,
    contact: "9678901234",
    location: "Lanka, Varanasi",
    availableTimeSlots: {
      weekdays: { morning: "9 AM - 1 PM", evening: "6 PM - 9 PM" },
      weekends: { morning: "9 AM - 1 PM", evening: "Closed" },
    },
    bio: "MD specializing in fever, diabetes, hypertension, and rheumatic diseases.",
    userId: "seed_doc17",
    updatedAt: new Date(),
  },
   // --- New Doctors from provided JSON ---
  {
    id: "doc18",
    name: "डॉ. रमेश शर्मा",
    clinicName: "बनारस हेल्थकेयर क्लिनिक",
    qualification: "एमडी मेडिसिन",
    specialization: "जनरल फ़िज़िशियन",
    experience: 10,
    consultationFee: 500,
    contact: "9876543210",
    location: "लक्सा रोड, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Experienced general physician serving the Varanasi area.",
    userId: "seed_doc18",
    updatedAt: new Date(),
  },
  {
    id: "doc19",
    name: "डॉ. सुनीता वर्मा",
    clinicName: "नारी शक्ति अस्पताल",
    qualification: "एमबीबीएस, एमएस (ओबी-जीवाईएन)",
    specialization: "स्त्री रोग विशेषज्ञ",
    experience: 12,
    consultationFee: 700,
    contact: "8765432109",
    location: "लंका रोड, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Dedicated to women's health and wellness.",
    userId: "seed_doc19",
    updatedAt: new Date(),
  },
  {
    id: "doc20",
    name: "डॉ. आशीष कुमार",
    clinicName: "बाल संजीवनी क्लिनिक",
    qualification: "एमडी (बाल रोग)",
    specialization: "बाल रोग विशेषज्ञ",
    experience: 8,
    consultationFee: 600,
    contact: "7654321098",
    location: "सिगरा, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Caring pediatrician for your little ones.",
    userId: "seed_doc20",
    updatedAt: new Date(),
  },
  {
    id: "doc21",
    name: "डॉ. प्रिया सिंह",
    clinicName: "स्किन केयर सेंटर",
    qualification: "एमबीबीएस, एमडी (डर्मेटोलॉजी)",
    specialization: "डर्मेटोलॉजिस्ट",
    experience: 7,
    consultationFee: 650,
    contact: "6543210987",
    location: "रविंद्रपुरी, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Expert in skin and hair treatments.",
    userId: "seed_doc21",
    updatedAt: new Date(),
  },
  {
    id: "doc22",
    name: "डॉ. अजय गुप्ता",
    clinicName: "हड्डी रोग अस्पताल",
    qualification: "एमएस (हड्डी रोग)",
    specialization: "हड्डी रोग विशेषज्ञ",
    experience: 15,
    consultationFee: 800,
    contact: "9876501234",
    location: "महमूरगंज, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Specialist in orthopedic surgery and treatments.",
    userId: "seed_doc22",
    updatedAt: new Date(),
  },
  {
    id: "doc23",
    name: "डॉ. नीता अग्रवाल",
    clinicName: "काशी नेत्रालय",
    qualification: "एमएस (नेत्र रोग)",
    specialization: "नेत्र रोग विशेषज्ञ",
    experience: 10,
    consultationFee: 550,
    contact: "8765498765",
    location: "ऑर्डरली बाजार, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Comprehensive eye care services.",
    userId: "seed_doc23",
    updatedAt: new Date(),
  },
  {
    id: "doc24",
    name: "डॉ. विवेक मिश्रा",
    clinicName: "स्माइल डेंटर क्लिनिक",
    qualification: "बीडीएस",
    specialization: "दंत चिकित्सक",
    experience: 5,
    consultationFee: 400,
    contact: "7654387654",
    location: "दुर्गाकुंड, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Your partner for a healthy smile.",
    userId: "seed_doc24",
    updatedAt: new Date(),
  },
  {
    id: "doc25",
    name: "डॉ. राज मोहन",
    clinicName: "बीएचयू हार्ट सेंटर",
    qualification: "एमडी, डीएम (कार्डियोलॉजी)",
    specialization: "कार्डियोलॉजिस्ट",
    experience: 20,
    consultationFee: 1000,
    contact: "9876576543",
    location: "लंका, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Leading cardiologist at BHU.",
    userId: "seed_doc25",
    updatedAt: new Date(),
  },
  {
    id: "doc26",
    name: "डॉ. किरण सिंह",
    clinicName: "राणा ENT अस्पताल",
    qualification: "एमएस (ईएनटी)",
    specialization: "ईएनटी विशेषज्ञ",
    experience: 12,
    consultationFee: 700,
    contact: "8765465432",
    location: "सिगरा, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Specialist for ear, nose, and throat conditions.",
    userId: "seed_doc26",
    updatedAt: new Date(),
  },
  {
    id: "doc27",
    name: "डॉ. अशोक पटेल",
    clinicName: "गंगा गैस्ट्रो क्लिनिक",
    qualification: "एमडी, डीएम (गेस्ट्रोएंट्रोलॉजी)",
    specialization: "गेस्ट्रोएंट्रोलॉजिस्ट",
    experience: 14,
    consultationFee: 900,
    contact: "7654354321",
    location: "चितईपुर, वाराणसी",
    availableTimeSlots: {
      weekdays: { morning: "10:00 AM - 1:00 PM", evening: "5:00 PM - 8:00 PM" },
      weekends: { morning: "11:00 AM - 2:00 PM", evening: "Closed" },
    },
    bio: "Expert care for digestive system disorders.",
    userId: "seed_doc27",
    updatedAt: new Date(),
  },
];


export const seedLabs: Lab[] = [
    {
        id: "lab1",
        labName: "Modern Pathology Lab",
        technicianName: "Mr. Rakesh Singh",
        address: "Bhelupur, Varanasi",
        registrationID: "LABVNS001",
        services: "Blood Test, Urine Test, Sugar Test, Thyroid Profile",
        charges: "Varies per test. Basic blood test starts at ₹150.",
        homeCollection: true,
        userId: "seed_lab1",
        updatedAt: new Date(),
    },
     {
        id: "lab2",
        labName: "Accurate Diagnostics",
        technicianName: "Ms. Sunita Patel",
        address: "Lanka, Varanasi",
        registrationID: "LABVNS002",
        services: "X-Ray, Ultrasound, CT Scan, MRI",
        charges: "X-Ray starts at ₹300. Advanced imaging as per rate card.",
        homeCollection: false,
        userId: "seed_lab2",
        updatedAt: new Date(),
    },
     {
        id: "lab3",
        labName: "Varanasi Health Scans",
        technicianName: "Mr. Anand Kumar",
        address: "Mahmoorganj, Varanasi",
        registrationID: "LABVNS003",
        services: "Full Body Checkup, Cardiac Markers, Cancer Markers",
        charges: "Health packages start from ₹999.",
        homeCollection: true,
        userId: "seed_lab3",
        updatedAt: new Date(),
    }
];

export const seedMedicalStores: MedicalStore[] = [
  {
    id: "1",
    storeName: "अरविंद मेडिकल स्टोर",
    ownerName: "Arvind Ji",
    address: "सोनिया रोड, कस्तूरबा नगर, सिगरा, वाराणसी, उत्तर प्रदेश 221010",
    licenseNo: "UPVNS001",
    contact: "+91 81125 55777",
    offers: "होम डिलीवरी, ब्लड टेस्ट की सुविधा",
    userId: "seed_ms1",
    updatedAt: new Date()
  },
  {
    id: "2",
    storeName: "बनारस फार्मेसी",
    ownerName: "Owner",
    address: "सोनी रोड, कस्तूरबा नगर, सिगरा, वाराणसी, उत्तर प्रदेश 221010",
    licenseNo: "UPVNS002",
    contact: "+91 98380 12345",
    offers: "24 घंटे खुली रहती है, सभी एलोपैथिक दवाएं",
    userId: "seed_ms2",
    updatedAt: new Date()
  },
  {
    id: "3",
    storeName: "मेडीवेरी फार्मेसी",
    ownerName: "Owner",
    address: "सिगरा, वाराणसी, उत्तर प्रदेश 221010",
    licenseNo: "UPVNS003",
    contact: "+91 70000 54321",
    offers: "ऑनलाइन डिलीवरी, त्वरित सेवा",
    userId: "seed_ms3",
    updatedAt: new Date()
  },
  {
    id: "4",
    storeName: "दवा मेडिकल एंड जनरल स्टोर्स",
    ownerName: "Owner",
    address: "माधव मार्केट, लंका, वाराणसी, उत्तर प्रदेश 221005",
    licenseNo: "UPVNS004",
    contact: "+91 94500 11111",
    offers: "जनरल और सर्जिकल आइटम",
    userId: "seed_ms4",
    updatedAt: new Date()
  },
  {
    id: "5",
    storeName: "अमर मेडिकल",
    ownerName: "Owner",
    address: "बीएचयू परिसर के पास, लंका, वाराणसी, उत्तर प्रदेश 221005",
    licenseNo: "UPVNS005",
    contact: "+91 80000 22222",
    offers: "कॉस्मेटिक उत्पाद",
    userId: "seed_ms5",
    updatedAt: new Date()
  },
  {
    id: "6",
    storeName: "न्यू रेखा मेडिकल एंड जनरल स्टोर",
    ownerName: "Owner",
    address: "बीएचयू गेट के पास, लंका, वाराणसी, उत्तर प्रदेश 221005",
    licenseNo: "UPVNS006",
    contact: "+91 93350 33333",
    offers: "24 घंटे खुली रहती है",
    userId: "seed_ms6",
    updatedAt: new Date()
  },
  {
    id: "7",
    storeName: "उमंग फार्मेसी",
    ownerName: "Owner",
    address: "सर सुंदरलाल अस्पताल, बीएचयू, लंका, वाराणसी, उत्तर प्रदेश 221005",
    licenseNo: "UPVNS007",
    contact: "+91 88888 44444",
    offers: "हॉस्पिटल फार्मेसी, 24 घंटे खुली रहती है",
    userId: "seed_ms7",
    updatedAt: new Date()
  },
  {
    id: "8",
    storeName: "सिद्धेश्वरी मेडिकल स्टोर",
    ownerName: "Owner",
    address: "डीएलडब्ल्यू, मंडुआडीह, वाराणसी, उत्तर प्रदेश 221004",
    licenseNo: "UPVNS008",
    contact: "+91 94150 55555",
    offers: "सभी प्रकार की दवाएं",
    userId: "seed_ms8",
    updatedAt: new Date()
  },
  {
    id: "9",
    storeName: "राज मेडिकल हॉल",
    ownerName: "Owner",
    address: "डीएलडब्ल्यू के पास, मंडुआडीह, वाराणसी, उत्तर प्रदेश 221004",
    licenseNo: "UPVNS009",
    contact: "+91 93360 66666",
    offers: "एलोपैथिक, आयुर्वेदिक और पशु चिकित्सा दवाएं",
    userId: "seed_ms9",
    updatedAt: new Date()
  },
  {
    id: "10",
    storeName: "शर्मा मेडिकल हॉल",
    ownerName: "Owner",
    address: "डीएलडब्ल्यू के पास, मंडुआडीह, वाराणसी, उत्तर प्रदेश 221004",
    licenseNo: "UPVNS010",
    contact: "+91 94510 77777",
    offers: "सभी दवाएं उपलब्ध",
    userId: "seed_ms10",
    updatedAt: new Date()
  },
  {
    id: "11",
    storeName: "जी.पी. मेडिकल्स",
    ownerName: "Owner",
    address: "चेतगंज, वाराणसी, उत्तर प्रदेश 221001",
    licenseNo: "UPVNS011",
    contact: "+91 99561 26545",
    offers: "50 वर्षों से सेवा, होम डिलीवरी, सस्ती दवाएं",
    userId: "seed_ms11",
    updatedAt: new Date()
  },
  {
    id: "12",
    storeName: "फैजान मेडिकल स्टोर",
    ownerName: "Owner",
    address: "लालापुरा, चेतगंज, वाराणसी, उत्तर प्रदेश 221001",
    licenseNo: "UPVNS012",
    contact: "+91 94550 88888",
    offers: "विश्वसनीय सेवा",
    userId: "seed_ms12",
    updatedAt: new Date()
  },
  {
    id: "13",
    storeName: "दवा दोस्त",
    ownerName: "Owner",
    address: "रेलवे स्टेशन परिसर के अंदर, वाराणसी जंक्शन, वाराणसी, उत्तर प्रदेश 221002",
    licenseNo: "UPVNS013",
    contact: "+91 94150 99999",
    offers: "24 घंटे खुली रहती है",
    userId: "seed_ms13",
    updatedAt: new Date()
  },
  {
    id: "14",
    storeName: "प्रधानमंत्री जन औषधि केंद्र",
    ownerName: "Government",
    address: "विद्यापीठ रोड, वाराणसी कैंट, वाराणसी, उत्तर प्रदेश 221002",
    licenseNo: "UPVNS014",
    contact: "+91 94116 94605",
    offers: "जेनेरिक दवाएं",
    userId: "seed_ms14",
    updatedAt: new Date()
  },
  {
    id: "15",
    storeName: "पुरी मेडिकल शॉप",
    ownerName: "Owner",
    address: "इंग्लिशिया लाइन रोड, कैंटोनमेंट, वाराणसी, उत्तर प्रदेश 221002",
    licenseNo: "UPVNS015",
    contact: "+91 94512 11111",
    offers: "त्वरित सेवा",
    userId: "seed_ms15",
    updatedAt: new Date()
  },
  {
    id: "500",
    storeName: "जन सेवा औषाधालय",
    ownerName: "Owner",
    address: "गोविंद स्वीट्स के पास, आर्डरली बाजार, वाराणसी, उत्तर प्रदेश 221002",
    licenseNo: "UPVNS500",
    contact: "+91 94155 99999",
    offers: "सुविधाजनक स्थान",
    userId: "seed_ms500",
    updatedAt: new Date()
  }
];


export const seedYogaCenters: YogaCenter[] = [
    {
        id: "yoga1",
        centerName: "Kashi Yoga Shala",
        instructorName: "Yogi Adityanath",
        address: "Assi Ghat, Varanasi",
        classTypes: "Hatha, Ashtanga, Meditation",
        schedule: "Mon-Sat: 6-8 AM & 5-7 PM",
        fee: "₹2500/month",
        onlineClasses: true,
        bio: "Traditional yoga taught on the serene banks of the Ganges.",
        userId: "seed_yoga1",
        updatedAt: new Date(),
    },
    {
        id: "yoga2",
        centerName: "Varanasi Wellness Center",
        instructorName: "Priya Sharma",
        address: "Nadesar, Varanasi",
        classTypes: "Vinyasa, Power Yoga, Prenatal Yoga",
        schedule: "Mon-Fri: 7-8 AM, 6-7 PM",
        fee: "₹3000/month, ₹400/class",
        onlineClasses: true,
        bio: "A modern studio focusing on fitness and wellness through dynamic yoga flows.",
        userId: "seed_yoga2",
        updatedAt: new Date(),
    }
];

export const seedAmbulances: Ambulance[] = [
  {
    id: "amb201",
    driverName: "जीवनधारा एम्बुलेंस",
    numberPlate: "UP65 AB 0201",
    vehicleType: "सामान्य",
    charges: "As per distance",
    status: true,
    contact: "9876543210",
    serviceArea: "लंका, वाराणसी",
    userId: "seed_amb_201",
    updatedAt: new Date(),
    location: { latitude: 25.2989, longitude: 82.9899 },
  },
  {
    id: "amb202",
    driverName: "गंगा एम्बुलेंस सेवा",
    numberPlate: "UP65 AB 0202",
    vehicleType: "आईसीयू",
    charges: "As per distance",
    status: true,
    contact: "8765432109",
    serviceArea: "सिगरा, वाराणसी",
    userId: "seed_amb_202",
    updatedAt: new Date(),
    location: { latitude: 25.3180, longitude: 82.9915 },
  },
  {
    id: "amb203",
    driverName: "वाराणसी इमरजेंसी सर्विस",
    numberPlate: "UP65 AB 0203",
    vehicleType: "ट्रामा",
    charges: "As per distance",
    status: true,
    contact: "7654321098",
    serviceArea: "महमूरगंज, वाराणसी",
    userId: "seed_amb_203",
    updatedAt: new Date(),
    location: { latitude: 25.3040, longitude: 82.9820 },
  },
  {
    id: "amb204",
    driverName: "काशी एम्बुलेंस",
    numberPlate: "UP65 AB 0204",
    vehicleType: "शिशु",
    charges: "As per distance",
    status: true,
    contact: "6543210987",
    serviceArea: "भेलूपुर, वाराणसी",
    userId: "seed_amb_204",
    updatedAt: new Date(),
    location: { latitude: 25.3056, longitude: 82.9984 },
  },
    {
    id: "amb205",
    driverName: "पूर्वांचल मेडिकल एम्बुलेंस",
    numberPlate: "UP65 AB 0205",
    vehicleType: "एयर एम्बुलेंस",
    charges: "As per distance",
    status: true,
    contact: "9876501234",
    serviceArea: "चितईपुर, वाराणसी",
    userId: "seed_amb_205",
    updatedAt: new Date(),
    location: { latitude: 25.2760, longitude: 82.9925 },
  },
];
